-- CREACION DE LA BASE DE DATOS
CREATE DATABASE IF NOT EXISTS login_seguro;
USE login_seguro;

-- TABLA DE USUARIOS
CREATE TABLE IF NOT EXISTS Usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    claveHash VARCHAR(255) NOT NULL,
    creadoEn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABLA DE INTENTOS DE LOGIN PARA FUERZA BRUTA
CREATE TABLE IF NOT EXISTS IntentosLogin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    direccionIp VARCHAR(45) NOT NULL,
    fechaIntento TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
